version: '2'

services:
  postgres:
    image: mdillon/postgis:10-alpine       
    environment:
      - POSTGRES_USER=moana
      - POSTGRES_PASSWORD=yiuPh9eipiu2la9ie8gaifee
      - POSTGRES_DB=moana
    ports:
      - '25432:5432'  